language: java
jdk: openjdk8
before_install:
#  - mvn -version
#  - mvn clean package -Ptest
#  - cd docker
#  - ./run-docker.sh
#  - cd ..
  - echo $GPG_SECRET_KEYS | base64 --decode | gpg --import
  - echo $GPG_OWNERTRUST | base64 --decode | gpg --import-ownertrust

## Build and release to maven central
script:
  mvn -s .maven.xml clean deploy -DskipTests=true -B -U -Prelease