language: java - openjdk8
services:
  - docker
## export GPG details
before_install:
  - mvn clean package
  - docker/run-docker.sh
  - echo $GPG_SECRET_KEYS | base64 --decode | $GPG_EXECUTABLE --import
  - echo $GPG_OWNERTRUST | base64 --decode | $GPG_EXECUTABLE --import-ownertrust
## Build and release to maven central
script:
  mvn -s .maven.xml clean deploy -DskipTests=true -Prelease