language: java
jdk: openjdk8
before_install:
#  - mvn -version
#  - mvn clean package -Ptest
#  - cd docker
#  - ./run-docker.sh
#  - cd ..
  - gpg --list-keys
#  - export GPG_TTY=$(tty)
#  - echo $GPG_SECRET_KEYS
#  - echo $GPG_OWNERTRUST
#  - echo $GPG_SECRET_KEYS | base64 --decode | $GPG_EXECUTABLE --import
#  - echo $GPG_OWNERTRUST | base64 --decode | $GPG_EXECUTABLE --import-ownertrust

## Build and release to maven central
script:
  mvn -s .maven.xml clean deploy -DskipTests=true -B -U -Prelease