language: java - openjdk8

services:
  - docker

before_install:
  - docker pull carlad/sinatra
  - docker images

before_deploy:
  - mvn help:evaluate -N -Dexpression=project.version|grep -v '\['
  - export project_version=$(mvn help:evaluate -N -Dexpression=project.version|grep
  -v '\[')


