language: java - openjdk8
## export GPG details
before_install:
#  - mvn -version
#  - mvn clean package -Ptest
#  - docker/run-docker.sh
  - echo $GPG_SECRET_KEYS | base64 --decode | $GPG_EXECUTABLE --import
  - echo $GPG_OWNERTRUST | base64 --decode | $GPG_EXECUTABLE --import-ownertrust
install:
  - mvn clean package -Ptest
## Build and release to maven central
script:
  mvn -s .maven.xml clean deploy -DskipTests=true -Prelease