language: java - openjdk8
services:
  - docker
## export GPG details
before_install:
#  - mvn clean package
#  - cd docker
#  - ./run-docker.sh
  - echo $GPG_SECRET_KEYS | base64 --decode | $GPG_EXECUTABLE --import
  - echo $GPG_OWNERTRUST | base64 --decode | $GPG_EXECUTABLE --import-ownertrust
install:
  mvn -s .maven.xml install -DskipTests=true -Dgpg.skip -Dmaven.javadoc.skip=true -B -V
## Build and release to maven central
script:
  mvn clean deploy -s .maven.xml -DskipTests=true -B -U -Prelease